# Generated by Django 4.1.5 on 2023-01-09 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={'verbose_name': 'Mentor', 'verbose_name_plural': 'Mentor'},
        ),
        migrations.AddField(
            model_name='student',
            name='academy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.academy'),
            preserve_default=False,
        ),
    ]
