# Generated by Django 4.1.5 on 2023-01-09 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_student_academy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='academy',
        ),
    ]
